export const DEPARTMENTS = {
  '91': { code: '91', name: 'Amazonas' },
  '05': { code: '05', name: 'Antioquia' },
  '81': { code: '81', name: 'Arauca' },
  '08': { code: '08', name: 'Atlántico' },
  '11': { code: '11', name: 'Bogotá' },
  '13': { code: '13', name: 'Bolívar' },
  '15': { code: '15', name: 'Boyacá' },
  '17': { code: '17', name: 'Caldas' },
  '18': { code: '18', name: 'Caquetá' },
  '85': { code: '85', name: 'Casanare' },
  '19': { code: '19', name: 'Cauca' },
  '20': { code: '20', name: 'Cesar' },
  '27': { code: '27', name: 'Chocó' },
  '23': { code: '23', name: 'Córdoba' },
  '25': { code: '25', name: 'Cundinamarca' },
  '94': { code: '94', name: 'Guainía' },
  '95': { code: '95', name: 'Guaviare' },
  '41': { code: '41', name: 'Huila' },
  '44': { code: '44', name: 'La Guajira' },
  '47': { code: '47', name: 'Magdalena' },
  '50': { code: '50', name: 'Meta' },
  '52': { code: '52', name: 'Nariño' },
  '54': { code: '54', name: 'Norte de Santander' },
  '86': { code: '86', name: 'Putumayo' },
  '63': { code: '63', name: 'Quindío' },
  '66': { code: '66', name: 'Risaralda' },
  '88': { code: '88', name: 'San Andrés y Providencia' },
  '68': { code: '68', name: 'Santander' },
  '70': { code: '70', name: 'Sucre' },
  '73': { code: '73', name: 'Tolima' },
  '76': { code: '76', name: 'Valle del Cauca' },
  '97': { code: '97', name: 'Vaupés' },
  '99': { code: '99', name: 'Vichada' },
} as const;

export type DepartmentCode = keyof typeof DEPARTMENTS;
export type DepartmentEntry = typeof DEPARTMENTS[DepartmentCode];
