export const LANGUAGES = {
  'aa': { code: 'aa', name: 'Afar' },
  'ab': { code: 'ab', name: 'Abkhazian' },
  'ae': { code: 'ae', name: 'Avestan' },
  'af': { code: 'af', name: 'Afrikaans' },
  'ak': { code: 'ak', name: 'Akan' },
  'am': { code: 'am', name: 'Amharic' },
  'an': { code: 'an', name: 'Aragonese' },
  'ar': { code: 'ar', name: 'Arabic' },
  'as': { code: 'as', name: 'Assamese' },
  'av': { code: 'av', name: 'Avaric' },
  'ay': { code: 'ay', name: 'Aymara' },
  'az': { code: 'az', name: 'Azerbaijani' },
  'ba': { code: 'ba', name: 'Bashkir' },
  'be': { code: 'be', name: 'Belarusian' },
  'bg': { code: 'bg', name: 'Bulgarian' },
  'bh': { code: 'bh', name: 'Bihari languages' },
  'bi': { code: 'bi', name: 'Bislama' },
  'bm': { code: 'bm', name: 'Bambara' },
  'bn': { code: 'bn', name: 'Bengali' },
  'bo': { code: 'bo', name: 'Tibetan' },
  'br': { code: 'br', name: 'Breton' },
  'bs': { code: 'bs', name: 'Bosnian' },
  'ca': { code: 'ca', name: 'Catalan; Valencian' },
  'ce': { code: 'ce', name: 'Chechen' },
  'ch': { code: 'ch', name: 'Chamorro' },
  'co': { code: 'co', name: 'Corsican' },
  'cr': { code: 'cr', name: 'Cree' },
  'cs': { code: 'cs', name: 'Czech' },
  'cu': { code: 'cu', name: 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic' },
  'cv': { code: 'cv', name: 'Chuvash' },
  'cy': { code: 'cy', name: 'Welsh' },
  'da': { code: 'da', name: 'Danish' },
  'de': { code: 'de', name: 'German' },
  'dv': { code: 'dv', name: 'Divehi; Dhivehi; Maldivian' },
  'dz': { code: 'dz', name: 'Dzongkha' },
  'ee': { code: 'ee', name: 'Ewe' },
  'el': { code: 'el', name: 'Greek; Modern (1453-)' },
  'en': { code: 'en', name: 'English' },
  'eo': { code: 'eo', name: 'Esperanto' },
  'es': { code: 'es', name: 'Spanish; Castilian' },
  'et': { code: 'et', name: 'Estonian' },
  'eu': { code: 'eu', name: 'Basque' },
  'fa': { code: 'fa', name: 'Persian' },
  'ff': { code: 'ff', name: 'Fulah' },
  'fi': { code: 'fi', name: 'Finnish' },
  'fj': { code: 'fj', name: 'Fijian' },
  'fo': { code: 'fo', name: 'Faroese' },
  'fr': { code: 'fr', name: 'French' },
  'fy': { code: 'fy', name: 'Western Frisian' },
  'ga': { code: 'ga', name: 'Irish' },
  'gd': { code: 'gd', name: 'Gaelic; Scottish Gaelic' },
  'gl': { code: 'gl', name: 'Galician' },
  'gn': { code: 'gn', name: 'Guarani' },
  'gu': { code: 'gu', name: 'Gujarati' },
  'gv': { code: 'gv', name: 'Manx' },
  'ha': { code: 'ha', name: 'Hausa' },
  'he': { code: 'he', name: 'Hebrew' },
  'hi': { code: 'hi', name: 'Hindi' },
  'ho': { code: 'ho', name: 'Hiri Motu' },
  'hr': { code: 'hr', name: 'Croatian' },
  'ht': { code: 'ht', name: 'Haitian; Haitian Creole' },
  'hu': { code: 'hu', name: 'Hungarian' },
  'hy': { code: 'hy', name: 'Armenian' },
  'hz': { code: 'hz', name: 'Herero' },
  'ia': { code: 'ia', name: 'Interlingua (International Auxiliary Language Association)' },
  'id': { code: 'id', name: 'Indonesian' },
  'ie': { code: 'ie', name: 'Interlingue; Occidental' },
  'ig': { code: 'ig', name: 'Igbo' },
  'ii': { code: 'ii', name: 'Sichuan Yi; Nuosu' },
  'ik': { code: 'ik', name: 'Inupiaq' },
  'io': { code: 'io', name: 'Ido' },
  'is': { code: 'is', name: 'Icelandic' },
  'it': { code: 'it', name: 'Italian' },
  'iu': { code: 'iu', name: 'Inuktiut' },
  'ja': { code: 'ja', name: 'Japanese' },
  'jv': { code: 'jv', name: 'Javanese' },
  'ka': { code: 'ka', name: 'Georgian' },
  'kg': { code: 'kg', name: 'Kongo' },
  'ki': { code: 'ki', name: 'Kikuyu; Gikuyu' },
  'kj': { code: 'kj', name: 'Kuanyama; Kwanyama' },
  'kk': { code: 'kk', name: 'Kazakh' },
  'kl': { code: 'kl', name: 'Kalaallisut; Greenlandic' },
  'km': { code: 'km', name: 'Central Khmer' },
  'kn': { code: 'kn', name: 'Kannada' },
  'ko': { code: 'ko', name: 'Korean' },
  'kr': { code: 'kr', name: 'Kanuri' },
  'ks': { code: 'ks', name: 'Kashmiri' },
  'ku': { code: 'ku', name: 'Kurdish' },
  'kv': { code: 'kv', name: 'Komi' },
  'kw': { code: 'kw', name: 'Cornish' },
  'ky': { code: 'ky', name: 'Kirghiz; Kyrgyz' },
  'la': { code: 'la', name: 'Latin' },
  'lb': { code: 'lb', name: 'Luxembourgish; Letzeburgesch' },
  'lg': { code: 'lg', name: 'Ganda' },
  'li': { code: 'li', name: 'Limburgan; Limburger; Limburgish' },
  'ln': { code: 'ln', name: 'Lingala' },
  'lo': { code: 'lo', name: 'Lao' },
  'lt': { code: 'lt', name: 'Lithuanian' },
  'lu': { code: 'lu', name: 'Luba-Katanga' },
  'lv': { code: 'lv', name: 'Latvian' },
  'mg': { code: 'mg', name: 'Malagasy' },
  'mh': { code: 'mh', name: 'Marshallese' },
  'mi': { code: 'mi', name: 'Maori' },
  'mk': { code: 'mk', name: 'Macedonian' },
  'ml': { code: 'ml', name: 'Malayalam' },
  'mn': { code: 'mn', name: 'Mongolian' },
  'mo': { code: 'mo', name: 'Moldavian; Moldovan' },
  'mr': { code: 'mr', name: 'Marathi' },
  'ms': { code: 'ms', name: 'Malay' },
  'mt': { code: 'mt', name: 'Maltese' },
  'my': { code: 'my', name: 'Burmese' },
  'na': { code: 'na', name: 'Nauru' },
  'nb': { code: 'nb', name: 'Bokmal Norwegian; Norwegian Bokmal' },
  'nd': { code: 'nd', name: 'Ndebele; North; North Ndebele' },
  'ne': { code: 'ne', name: 'Nepali' },
  'ng': { code: 'ng', name: 'Ndonga' },
  'nl': { code: 'nl', name: 'Dutch; Flemish' },
  'nn': { code: 'nn', name: 'Norwegian Nynorsk; Nynorsk, Norwegian' },
  'no': { code: 'no', name: 'Norwegian' },
  'nr': { code: 'nr', name: 'Ndebele; South; South Ndebele' },
  'nv': { code: 'nv', name: 'Navajo; Navaho' },
  'ny': { code: 'ny', name: 'Chichewa; Chewa; Nyanja' },
  'oc': { code: 'oc', name: 'Occitan (post 1500)' },
  'oj': { code: 'oj', name: 'Ojibwa' },
  'om': { code: 'om', name: 'Oromo' },
  'or': { code: 'or', name: 'Oriya' },
  'os': { code: 'os', name: 'Ossetian; Ossetic' },
  'pa': { code: 'pa', name: 'Panjabi; Punjabi' },
  'pi': { code: 'pi', name: 'Pali' },
  'pl': { code: 'pl', name: 'Polish' },
  'ps': { code: 'ps', name: 'Pushto; Pashto' },
  'pt': { code: 'pt', name: 'Portuguese' },
  'qu': { code: 'qu', name: 'Quechua' },
  'rm': { code: 'rm', name: 'Romansh' },
  'rn': { code: 'rn', name: 'Rundi' },
  'ro': { code: 'ro', name: 'Romanian' },
  'ru': { code: 'ru', name: 'Russian' },
  'rw': { code: 'rw', name: 'Kinyarwanda' },
  'sa': { code: 'sa', name: 'Sanskrit' },
  'sc': { code: 'sc', name: 'Sardinian' },
  'sd': { code: 'sd', name: 'Sindhi' },
  'se': { code: 'se', name: 'Northern Sami' },
  'sg': { code: 'sg', name: 'Sango' },
  'si': { code: 'si', name: 'Sinhala; Sinhalese' },
  'sk': { code: 'sk', name: 'Slovak' },
  'sl': { code: 'sl', name: 'Slovenian' },
  'sm': { code: 'sm', name: 'Samoan' },
  'sn': { code: 'sn', name: 'Shona' },
  'so': { code: 'so', name: 'Somali' },
  'sq': { code: 'sq', name: 'Albanian' },
  'sr': { code: 'sr', name: 'Serbian' },
  'ss': { code: 'ss', name: 'Swati' },
  'st': { code: 'st', name: 'Sotho, Southern' },
  'su': { code: 'su', name: 'Sundanese' },
  'sv': { code: 'sv', name: 'Swedish' },
  'sw': { code: 'sw', name: 'Swahili' },
  'ta': { code: 'ta', name: 'Tamil' },
  'te': { code: 'te', name: 'Telugu' },
  'tg': { code: 'tg', name: 'Tajik' },
  'th': { code: 'th', name: 'Thai' },
  'ti': { code: 'ti', name: 'Tigrinya' },
  'tk': { code: 'tk', name: 'Turkmen' },
  'tl': { code: 'tl', name: 'Tagalog' },
  'tn': { code: 'tn', name: 'Tswana' },
  'to': { code: 'to', name: 'Tonga (Tonga Islands)' },
  'tr': { code: 'tr', name: 'Turkish' },
  'ts': { code: 'ts', name: 'Tsonga' },
  'tt': { code: 'tt', name: 'Tatar' },
  'tw': { code: 'tw', name: 'Twi' },
  'ty': { code: 'ty', name: 'Tahitian' },
  'ug': { code: 'ug', name: 'Uighur; Uyghur' },
  'uk': { code: 'uk', name: 'Ukrainian' },
  'ur': { code: 'ur', name: 'Urdu' },
  'uz': { code: 'uz', name: 'Uzbek' },
  've': { code: 've', name: 'Venda' },
  'vi': { code: 'vi', name: 'Vietnamese' },
  'vo': { code: 'vo', name: 'Volapük' },
  'wa': { code: 'wa', name: 'Walloon' },
  'wo': { code: 'wo', name: 'Wolof' },
  'xh': { code: 'xh', name: 'Xhosa' },
  'yi': { code: 'yi', name: 'Yiddish' },
  'yo': { code: 'yo', name: 'Yoruba' },
  'za': { code: 'za', name: 'Zhuang; Chuang' },
  'zh': { code: 'zh', name: 'Chinese' },
  'zu': { code: 'zu', name: 'Zulu' },
} as const;

export type LanguageCode = keyof typeof LANGUAGES;
export type LanguageEntry = typeof LANGUAGES[LanguageCode];
